[book]
authors = ["Spockuto"]
language = "en"
src = "src"
title = "log_coffee!"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
mathjax-support = true
no-section-label = true
additional-css = ["custom.css"]
git-repository-url = "https://github.com/Spockuto/blog"
git-repository-icon = "fas-code-fork"

[output.html.search]
limit-results = 15
